# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VvnfIx6PBOBQpEv_jaW3t7SJvMIC8erS
"""

!pip install transformers

from transformers import pipeline, set_seed

generator = pipeline('text-generation', model='gpt2')
set_seed(42)

prompt = "The future of artificial intelligence"
output = generator(prompt, max_length=100, num_return_sequences=1)

print(output[0]['generated_text'])

def generate_text(prompt):
    result = generator(prompt, max_length=100, num_return_sequences=1)
    print("\nGenerated Text:\n")
    print(result[0]['generated_text'])

# Example:
generate_text("How technology is changing education")